name: Run Go Tests

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - '**.go'
      - '**.mod'
      - '**.sum'
      - '**.proto'
      - 'Makefile'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      # Install and setup go
      - name: Set up Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20.0'

      # checkout horcrux
      - name: checkout horcrux
        uses: actions/checkout@v3

      # make sure proto files are up to date
      - name: generate fresh signer proto .go files
        run: make signer-proto

      # run tests
      - name: run horcrux tests
        run: make test
  e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test: 
          - Test2Of3SignerThreeSentries
          - Test2Of3SignerThreeSentriesUniqueConnection
          - Test3Of5SignerFiveSentriesUniqueConnection
          - TestSingleSignerTwoSentries
          - TestUpgradeValidatorToHorcrux
          - TestDownedSigners2of3
          - TestLeaderElection2of3
          - TestChainPureHorcrux
          - TestMultipleChainHorcrux
    steps:
      # Install and setup go
      - name: Set up Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20.0'

      # checkout horcrux
      - name: checkout horcrux
        uses: actions/checkout@v3

      # make sure proto files are up to date
      - name: generate fresh signer proto .go files
        run: make signer-proto

      # run test matrix
      - name: run test
        run: cd test && go test -v -timeout 30m -run ^${{ matrix.test }}$ .
